-- SELECT 를 통한 테이블 복사
-- CREATE TABLE ... AS SELECT
-- CATEATE TABLE 새테이블명 AS SELECT 복사할 열 FROM 원본테이블명 WHERE 조건

-- 테이블복사 : 기본키는 복사안됨(제약조건은 따로 추가)
CREATE TABLE NEWBOOK AS
SELECT * FROM BOOK WHERE BOOKDATE >= '2019-01-01';

SELECT * FROM NEWBOOK;

-- 제약조건은 복사되지 않으므로 수정 작업
ALTER TABLE NEWBOOK
    ADD CONSTRAINT PK_NEWBOOK_BOOKNO
    PRIMARY KEY(BOOKNO);
    
-- NEWBOOK 데이터 삭제
DELETE FROM NEWBOOK;

SELECT * FROM NEWBOOK;

-- 빈 테이블에 다른 테이블의 SELECT 결과로 데이터 저장
-- (BOOK과 NEWBOOK의 컬럼 구조가 동일할 때)
INSERT INTO NEWBOOK
SELECT * FROM BOOK;

SELECT * FROM NEWBOOK;

-- 테이블 생성(CTAS): BOOK에서 BOOKNO, BOOKNAME 두 컬럼만 복사해 새 테이블 만들기
CREATE TABLE NEWBOOK2 AS
SELECT BOOKNO, BOOKNAME
FROM BOOK;

SELECT * FROM NEWBOOK2;

DELETE FROM NEWBOOK2;

-- NEWBOOK2 테이블에 BOOK 테이블의 BOOKNO, BOOKNAME을 복사해서 저장
INSERT INTO NEWBOOK2 (BOOKNO, BOOKNAME)
SELECT BOOKNO, BOOKNAME
FROM BOOK;

SELECT * FROM NEWBOOK2;


